### ISSUE TITLE
use Generic.Rep

### ISSUE THREAD

**Issue by coot** [eskimor/purescript-bridge#33]
Purescript's `Generic` will not be derivable in `purscript-0.12` (it isn't in the master already).  The alternative is to use `Data.Generic.Rep` instead.

**Comment by eskimor** [comment]
Thank you for the heads up!

**Comment by coot** [comment]
I'll take a look into this.

**Comment by eskimor** [comment]
@coot awesome! :-)

**Comment by CarstenKoenig** [comment]
Hi,

I think we will need this very soon (PureScript 0.12 will remove the compiler support for `purescript-generics` [see Release notes](https://github.com/purescript/purescript/releases/tag/v0.12.0))

Is it ok with you if I have a look at this?

---

as far as I can tell this will probably be the only road-block for this going straight into `purs 0.12` - all the other dependencies (including `purescript-profunctor-lenses` seem to be already ported to *0.12*)

**Comment by eskimor** [comment]
If you drop the generic-derives you no longer get automatic aeson compatible JSON encodings. purescript-argonaut-codecs seem to have abandoned generic JSON encoding - at least I can't find it in the current code base.

**Comment by CarstenKoenig** [comment]
I think they moved it to here: https://pursuit.purescript.org/packages/purescript-argonaut-generic/1.2.0

But this one is not ready for 0.12 either

No matter what, the *deriving* of `purescript-generic` will be gone with 0.12 and it's moved to `generic-rep`

---

But didn't you reimplement the generic argonaut stuff [here](https://github.com/eskimor/purescript-argonaut-generic-codecs) in the first place? I thought the only questions was if we want to replace or update this.

**Comment by eskimor** [comment]
> But didn't you reimplement the generic argonaut stuff here in the first place? I thought the only questions was if we want to replace or update this.

Right - you pointed to purescript-argonaut, so I just looked what they did for 0.12. The library we would need to update/replace is of course [that one](https://github.com/eskimor/purescript-argonaut-generic-codecs).

**Comment by eskimor** [comment]
Well, as far as I understood Generics.Rep work similar to Haskell Generics. That means: Fundamentally different than the old PS Generics. It would definitely not be a drop in replacement. For example, in order to override the generic JSON encoding one would no longer use [userEncoding](https://github.com/eskimor/purescript-argonaut-generic-codecs/blob/master/src/Data/Argonaut/Generic/Options.purs#L32), but simply would provide handwritten instances for`ToJSON`, `FromJSON` for the type in question. 

The most fundamental difference is that with Haskell Generics you don't recursively walk the data type, but simply provide a `ToJSON` implementation for the current data type in question, by leveraging `ToJSON` instances already existing for data types "contained" in your data type.

In PS Generics you would simple walk the entire data type including all predefined data types used in your type and produce JSON as you go.

Example:

```haskell
data MyType = MyType SomeOtherType
```

With Haskell generics, you would simply use the `ToJSON` instance of `SomeOtherType` for implementing a `Generic` `ToJSON` instance for `MyType`. In PS, the `ToJSON` instance fo `SomeOtherType` is completely irrelevant.

Having a glimpse at `RowToList` it seems, it made make some things easier when dealing with records.

**Comment by CarstenKoenig** [comment]
yes it does - and I think I can just add this to get the missing parts from `Generics.Rep` (they dropped the Record and Row-List field representations)

Btw: thanks for the explanation

**Comment by CarstenKoenig** [comment]
btw: I was able to get a combination of both working here: https://github.com/CarstenKoenig/purescript-argonaut-generic/tree/RowToList

I filed a WIP-PR there and if this is merged I would recommend we just derive the `generic-rep` here and use this for `purescript-servant`

**Comment by eskimor** [comment]
someone's a fast typer ... :-)

**Comment by shmish111** [comment]
@CarstenKoenig can this be closed now?

**Comment by CarstenKoenig** [comment]
I think so yes

**Comment by peterbecich** [comment]
It appears the Generics Rep library has been deprecated; moved to Prelude: https://github.com/purescript-deprecated/purescript-generics-rep
